### ISSUE TITLE
Strip Content-Length header when Transfer-Encoding header is set on request and response

### ISSUE THREAD

**Issue by halter73** [aspnet/Proxy#30]
I seems the HTTP the spec suggests removing the content-length header when a transfer-encoding header is set.

>   If a message is received with both a Transfer-Encoding and a
>    Content-Length header field, the Transfer-Encoding overrides the
>    Content-Length.  Such a message might indicate an attempt to
>    perform request smuggling (Section 9.5) or response splitting
>    (Section 9.4) and ought to be handled as an error.  A sender MUST
>    remove the received Content-Length field prior to forwarding such
>    a message downstream.
> https://tools.ietf.org/html/rfc7230#section-3.3.3

https://github.com/aspnet/KestrelHttpServer/pull/1163#discussion_r83061038

**Comment by Tratcher** [comment]
Proxy already strips Transfer-Encoding because HttpClient removed the chunked framing and the underlying server needs (Kestrel) to re-add it.

**Comment by Marusyk** [comment]
@Tratcher  When HttpClient remove the chunked and why? Thanks

**Comment by mkosieradzki** [comment]
@Marusyk 
Because there are three states:
1. content-length is specified - then transfer is done classic way
2. no chunked encoding header is specified then chunked encoding is autohandled by ASP.NET Core
3. chunked encoding header is specified and developer is responsible for chunked encoding implementation.

After proxying request you when you receive response from destination server it can contain chunked encoding header. You don't want to handle it manually so it is removed.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2501
